version: '3'

services:
  api:
    image: "node:14"
    networks:
      - base_network
    ports:
      - "3000:3000"
    command: sh -c "npm run start:dev"
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      NODE_ENV: development

networks:
  base_network:
